In [2]:
#pip install numpy
import numpy as np
a=np.array([1,2])
a

array([1, 2])

In [3]:
b=np.array([[1,2,3,5],[5,7,8,9]])
b

array([[1, 2, 3, 5],
       [5, 7, 8, 9]])

In [4]:
b.ndim # To find dimensions

2

In [5]:
b.shape #(rows,col)

(2, 4)

In [6]:
b.dtype # To find the data type

dtype('int32')

In [7]:
a.dtype

dtype('int32')

In [8]:
b.itemsize # It gives one item occupied space in memory.As data type is int it occupies 4bytes

4

In [9]:
a.nbytes

8

In [10]:
b.nbytes


32

In [11]:
a[0]

1

In [12]:
a[1]

2

In [13]:
b[0,1]

2

In [14]:
b[1,1]

7

In [15]:
b[1,0] # [rows,columns]

5

In [16]:
b[0,0]

1

In [17]:
b[0,2]

3

In [18]:
b[0,:] # Used to print first row elements

array([1, 2, 3, 5])

In [19]:
c=np.array([[1,2,3,4,5,6,7,8,9],[9,8,7,6,5,4,3,2,1]])
c

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5, 4, 3, 2, 1]])

In [20]:
c[0,:2]

array([1, 2])

In [21]:
c[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
c[:,2]

array([3, 7])

In [23]:
c[:,7]# specific total col

array([8, 2])

In [24]:
d=np.array([[[1,2,0],[3,4,7],[5,6,2],[7,8,3]]])
d

array([[[1, 2, 0],
        [3, 4, 7],
        [5, 6, 2],
        [7, 8, 3]]])

In [25]:
d[0,:]

array([[1, 2, 0],
       [3, 4, 7],
       [5, 6, 2],
       [7, 8, 3]])

In [26]:
d[:,0]

array([[1, 2, 0]])

In [27]:
d.ndim

3

In [28]:
s=np.zeros((2,3) , dtype=int)
s

array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
s=np.zeros((2,3,2),dtype= int)
s

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [30]:
s=np.ones((2,3,2),dtype= bool)
s

array([[[ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True]]])

# FUNCTIONS
#1.arange(start,end(exclusive), step(not complusory to give))


In [31]:
a=np.arange(1,20)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [32]:
a=np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
#2.reshape((rows,cols))
a=a.reshape((3,3))
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [34]:
b=np.arange(1,100,1)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [35]:
b=b.reshape((5,10))
b

ValueError: cannot reshape array of size 99 into shape (5,10)

In [ ]:
#3.flatten()# reverse process of reshaping.
#. convets to 1 row having multiple coloumns.
b=b.flatten()
b


 # find the difference between ravel() and flatten()?


In [ ]:
b=b.ravel() 
b

# indexing and slicing.

In [ ]:
a=np.arange(1,51)
a=a.reshape(10,5)
a

In [ ]:
a[0]

In [ ]:
a[0,0]

In [ ]:
a[0,1]

In [ ]:
a[3,4]

In [ ]:
# a[a:b(exclusive)] used to print the rows
a[1:5]

In [ ]:
a[0:,2]

In [ ]:
a[1:,4] # 2nd row 5th coloum .# after keeping comma then we are talking about the columns.

In [ ]:
a[1,4]

In [ ]:
a[:,:] # printing total rows and columns

In [ ]:
# a[:,2(index of col):5(exclusive)]

In [ ]:
a[:,2:5]

In [ ]:
a[:,2:4].dtype

# mathematical operations

In [ ]:
a=np.arange(0,18).reshape((6,3))
b=np.arange(20,38).reshape((6,3))
print(a)
print(b)

In [ ]:
a+b

In [ ]:
a*b # here it is not matrix multiplication .

In [ ]:
a/b

In [ ]:
np.divide(a,b)

In [ ]:
#(a@b) # It is the matrix multiplication
#cond:no.of col in a should be equal to no.of rows in b.


In [ ]:
b=b.reshape((3,6))
b

In [ ]:
# It is the matrix multiplication.
a@b

In [ ]:
a.dot(b) # This also used for matrix multiplation.

In [ ]:
b.max()

In [ ]:
b.min()

In [ ]:
b.argmin() # this is the index of the mininum value number in b

In [ ]:
np.sum(b) # It will give the sum of all the elements of b array

In [ ]:
b

In [ ]:
# sum of elements in a row

In [ ]:
np.sum(b,axis = 1)

In [ ]:
np.sum(b,axis = 0) # sum of elements in a col of b array.

In [ ]:
np.mean(b)

In [ ]:
np.sqrt(b)

In [ ]:
np.std(b) # It gives the standard deviation of b.

In [ ]:
np.log(b)

# Trignometeric functions.

In [ ]:
#pip install matplotlib

In [ ]:
#conda install matplotlib

In [ ]:
np.pi

In [ ]:
np.sin(np.pi/2)

In [ ]:
np.tan(np.pi/2)

# Using matplotlib with numpy

In [ ]:
# import numpy as np
 #   import matplotlib as plt
  #  plt.style.use('dark_background')
  #  x=np.arange(1,11)
  #  y=np.arange(10,110,10)
#
 #   plt.figure(figsize = (6,6))
  #  plt.plot(x,y,'r--')
   # plot.show()

In [ ]:
#matplotlib is not working here .
import numpy as np

In [36]:
np.random.random(1)

array([0.49484215])

In [37]:
np.random.random(1)

array([0.11420225])

In [ ]:

np.random.random(2)

In [ ]:
np.random.random((2,2)) # A randomly generated 2d array

In [ ]:
np.random.randint(1,10)

In [ ]:
np.random.randint(1,10)

In [ ]:
np.random.randint(1,10,(2,2)) # Creating 2D array randomly.

In [ ]:
np.random.randint(1,10,(1,4,5))

In [ ]:
np.random.rand(2,2) # By using rand we can create float values

In [ ]:
np.random.randn(2,2) # we can get negatively values also 

In [ ]:
a=np.arange(1,10)
print(a)

In [ ]:
np.random.choice(a)

# Playing with strings

In [ ]:
s1='Jayanth is the winner'
s2= ' Iam an Indian'
np.char.add(s1, s2) # Used for concating of stirngs

In [ ]:
np.char.lower(s1)

In [ ]:
np.char.split(s1) # It will split into diff str when it find space

In [ ]:
np.char.replace(s1,'winner','ceo of google')

# The end of Numpy # 